"""Fail-closed reconciliation of simulator card data.

The repository's original ``CARD_METADATA`` table is a useful identity and
fallback catalog, but its numeric values are level-16 values.  Treating those
values as the Level-11 ruleset silently changes every interaction.  This
module therefore keeps two separate, deterministic inputs:

* a pinned Level-11 structured snapshot (comparison evidence), and
* field-level official balance overrides for the declared ``2026-08-04``
  ruleset.

The importer never promotes a disagreement to truth.  It emits a row for each
compared field and marks unresolved or unsupported values explicitly.  Runtime
ruleset generation uses the same official override table, while the CLI audit
can be run with a newer source snapshot without changing the simulator.
"""

from __future__ import annotations

from copy import deepcopy
import hashlib
import json
from pathlib import Path
from typing import Any, Mapping


SOURCE_DIRECTORY = Path(__file__).resolve().parent / "sources"
LEVEL11_SOURCE_PATH = SOURCE_DIRECTORY / "level11_card_stats.json"
OFFICIAL_OVERRIDE_PATH = SOURCE_DIRECTORY / "official_level11_overrides.json"
DECKSHOP_SOURCE_PATH = SOURCE_DIRECTORY / "deckshop_level11.json"
DECKSHOP_CORE_SOURCE_PATH = SOURCE_DIRECTORY / "deckshop_core_level11.json"
DECKSHOP_HEAL_SPIRIT_SOURCE_PATH = SOURCE_DIRECTORY / "deckshop_heal_spirit_level11.json"
LEVEL11_SOURCE_ID = "local-level11-card-stats-2026-04-12"
RECONCILIATION_SCHEMA_VERSION = 1


def _read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"expected a JSON object in {path}")
    return value


def load_level11_source(path: Path | None = None) -> dict[str, Any]:
    """Load the pinned structured comparison source, never from the network."""

    return _read_json(path or LEVEL11_SOURCE_PATH)


def load_official_overrides(path: Path | None = None) -> dict[str, Any]:
    """Load the field-level official patch table."""

    return _read_json(path or OFFICIAL_OVERRIDE_PATH)


def source_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_payload_sha256(payload: Mapping[str, Any]) -> str:
    """Hash an in-memory source exactly as the reconciliation report sees it."""

    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _override_rows() -> tuple[dict[str, Any], ...]:
    payload = load_official_overrides()
    rows = payload.get("overrides", [])
    if not isinstance(rows, list):
        raise ValueError("official override table must contain an overrides list")
    return tuple(row for row in rows if isinstance(row, dict))


def official_override_rows(card_id: str) -> tuple[dict[str, Any], ...]:
    """Return immutable-by-convention overrides for one canonical card ID."""

    rows = [row for row in _override_rows() if row.get("card_id") == card_id]
    spell_damage = load_official_overrides().get("spell_crown_tower_damage", {})
    if card_id in spell_damage:
        rows.append(
            {
                "card_id": card_id,
                "field": "crown_tower_damage",
                "value": spell_damage[card_id],
                "source_id": "official-june-2026-spell-crown-damage",
                "note": "June 2026 blanket spell Crown Tower damage reduction.",
            }
        )
    return tuple(rows)


def _set_path(mapping: dict[str, Any], path: str, value: Any) -> None:
    parts = path.split(".")
    cursor = mapping
    for part in parts[:-1]:
        child = cursor.get(part)
        if not isinstance(child, dict):
            child = {}
            cursor[part] = child
        cursor = child
    cursor[parts[-1]] = deepcopy(value)


def apply_official_overrides(
    card_id: str,
    definition: Mapping[str, Any],
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Apply official values to a generated card and return audit rows.

    The operation is deliberately limited to cards generated by
    :mod:`simulator.catalog`; high-confidence base cards remain byte-for-byte
    pinned in the checked-in ruleset.  Provenance is written per field, and an
    override never removes the card's broader provisional-mechanics marker.
    """

    raw = deepcopy(dict(definition))
    provenance = {
        str(key): list(value) if isinstance(value, (list, tuple)) else [str(value)]
        for key, value in dict(raw.get("provenance", {})).items()
    }
    applied: list[dict[str, Any]] = []
    for row in official_override_rows(card_id):
        field = row.get("field")
        if not isinstance(field, str) or not field:
            continue
        _set_path(raw, field, row.get("value"))
        source_id = str(row.get("source_id", "official-unknown"))
        values = provenance.setdefault(field, [])
        if source_id not in values:
            values.append(source_id)
        applied.append(
            {
                "card_id": card_id,
                "field": field,
                "resolved_value": deepcopy(row.get("value")),
                "source_id": source_id,
                "note": row.get("note"),
            }
        )
    raw["provenance"] = provenance
    return raw, applied


def _level11_source_rows(payload: Mapping[str, Any]) -> Mapping[str, Any]:
    rows = payload.get("cards", {})
    if not isinstance(rows, dict):
        raise ValueError("Level-11 source cards must be an object keyed by card ID")
    return rows


def _source_field(row: Mapping[str, Any], field: str) -> Any:
    if field == "elixir_milli":
        value = row.get("elixir_cost")
        return None if value is None else int(value) * 1_000
    if field == "hitpoints":
        return row.get("hitpoints")
    if field == "damage":
        return row.get("damage")
    if field == "crown_tower_damage":
        return row.get("tower_damage")
    if field == "attack_interval_us":
        value = row.get("attack_interval_s")
        return None if value is None else int(round(float(value) * 1_000_000))
    if field == "range_mtile":
        value = row.get("range_tiles")
        return None if value is None else int(round(float(value) * 1_000))
    if field == "area_radius_mtile":
        value = row.get("radius_tiles")
        return None if value is None else int(round(float(value) * 1_000))
    if field == "lifetime_us":
        value = row.get("duration_s")
        return None if value is None else int(round(float(value) * 1_000_000))
    if field == "spawn_count":
        return row.get("spawn_count")
    return row.get(field)


_COMPARE_FIELDS: tuple[str, ...] = (
    "elixir_milli",
    "hitpoints",
    "damage",
    "crown_tower_damage",
    "attack_interval_us",
    "range_mtile",
    "area_radius_mtile",
    "lifetime_us",
    "spawn_count",
)


def _is_passive_spawner_definition(definition: Mapping[str, Any]) -> bool:
    """Return whether a building has no executable attack component.

    Several historical structured snapshots expose the body/spawn damage of
    hut-like buildings in the generic ``damage`` column.  Those values are
    useful evidence for the child stream, but they are not a repeating weapon
    on the building itself.  Runtime catalog generation deliberately clears
    the attack fields for these cards.  Reconciliation must apply the same
    applicability rule or it would report a conflict for a mechanic that does
    not exist.
    """

    if str(definition.get("kind", "")) != "building":
        return False
    if any(
        definition.get(field) is not None
        for field in ("damage", "attack_interval_us", "range_mtile")
    ):
        return False
    mechanics = definition.get("mechanics", {})
    return isinstance(mechanics, Mapping) and (
        mechanics.get("spawn") is not None
        or mechanics.get("elixir_generation") is not None
        or mechanics.get("death") is not None
    )


def _get_path(mapping: Mapping[str, Any], path: str) -> Any:
    cursor: Any = mapping
    for part in path.split("."):
        if not isinstance(cursor, Mapping) or part not in cursor:
            return None
        cursor = cursor[part]
    return cursor


def _official_value(card_id: str, field: str) -> tuple[Any, str | None]:
    for row in official_override_rows(card_id):
        if row.get("field") == field:
            return row.get("value"), str(row.get("source_id"))
    return None, None


def reconcile_card(
    card_id: str,
    definition: Mapping[str, Any],
    source_row: Mapping[str, Any] | None,
    additional_source_rows: tuple[tuple[str, Mapping[str, Any] | None], ...] = (),
) -> list[dict[str, Any]]:
    """Compare one executable definition field-by-field.

    ``official`` wins over the structured source.  A source mismatch is still
    retained in the row so CI can show exactly what was overridden.  A missing
    source value or an unsupported official mechanic is never reported as an
    agreement.
    """

    rows: list[dict[str, Any]] = []
    for field in _COMPARE_FIELDS:
        simulator_value = _get_path(definition, field)
        # The structured card table also carries child-body stats for spell
        # projectiles (for example the Barbarian Barrel barrel HP).  Those are
        # not the executable spell card's scalar fields and must not be
        # mistaken for a conflict.
        kind = str(definition.get("kind", ""))
        # The structured table's ``duration_s`` field is polymorphic: for
        # spells it is an effect duration, and for several troop rows it is a
        # fuse/stealth/other child-effect duration rather than the body's
        # lifetime.  Only a building's duration is comparable to the
        # simulator's ``lifetime_us`` field.  Treating a troop's duration as
        # its lifetime manufactured conflicts such as Lumberjack=50 ms and
        # Ice Golem=1 s, which would incorrectly make a normal troop expire.
        passive_spawner = _is_passive_spawner_definition(definition)
        not_applicable = (
            (kind == "spell" and field in {
                "hitpoints",
                "attack_interval_us",
                "range_mtile",
                "lifetime_us",
                "spawn_count",
            })
            or (kind == "troop" and field == "lifetime_us")
            # Legacy hut/spawner rows may contain child-body damage, but a
            # passive building has no attack cadence/range/damage component.
            # Keep all attack-shaped fields explicitly non-applicable.
            or (passive_spawner and field in {
                "damage",
                "crown_tower_damage",
                "attack_interval_us",
                "range_mtile",
            })
        )
        structured_value = (
            None
            if source_row is None or not_applicable
            else _source_field(source_row, field)
        )
        additional_values = {
            source_id: _source_field(row, field)
            for source_id, row in additional_source_rows
            if row is not None and not not_applicable
        }
        matching_additional = any(
            value is not None and value == simulator_value
            for value in additional_values.values()
        )
        official_value, official_source = _official_value(card_id, field)
        if official_source is not None:
            resolved = official_value
            status = "verified_official"
            if structured_value is not None and structured_value != official_value:
                status = "official_override_conflict"
        elif not_applicable:
            resolved = simulator_value
            status = "not_applicable"
        elif matching_additional:
            resolved = simulator_value
            status = "independent_structured_match"
        elif structured_value is None and source_row is not None and simulator_value is None:
            resolved = simulator_value
            status = "not_applicable"
        elif structured_value is None:
            resolved = simulator_value
            status = "unresolved_missing_source"
        elif simulator_value == structured_value:
            resolved = simulator_value
            status = "structured_match"
        else:
            resolved = simulator_value
            status = "unresolved_source_conflict"
        rows.append(
            {
                "card_id": card_id,
                "field": field,
                "simulator_value": simulator_value,
                "structured_value": structured_value,
                "official_value": official_value,
                "official_source": official_source,
                "resolved_value": resolved,
                "status": status,
                "additional_structured_values": additional_values,
            }
        )

    # Mechanics are compared as explicit evidence too.  These fields often
    # cannot be represented by a single scalar and therefore must not be
    # silently flattened into damage/hit-speed columns.
    for override in official_override_rows(card_id):
        field = str(override.get("field"))
        if not field.startswith("mechanics."):
            continue
        simulator_value = _get_path(definition, field)
        rows.append(
            {
                "card_id": card_id,
                "field": field,
                "simulator_value": simulator_value,
                "structured_value": None,
                "official_value": override.get("value"),
                "official_source": override.get("source_id"),
                "resolved_value": override.get("value"),
                "status": "verified_official" if simulator_value == override.get("value") else "official_override_conflict",
            }
        )
    return rows


def reconcile_ruleset(
    ruleset: Any,
    *,
    source_payload: Mapping[str, Any] | None = None,
    source_path: Path | None = None,
    additional_sources: tuple[tuple[str, Mapping[str, Any]], ...] = (),
) -> dict[str, Any]:
    """Build a JSON-serializable report for every interaction-set card."""

    if source_payload is not None and source_path is not None:
        raise ValueError("provide source_payload or source_path, not both")
    source = dict(source_payload) if source_payload is not None else load_level11_source(source_path)
    source_rows = _level11_source_rows(source)
    card_rows: list[dict[str, Any]] = []
    for card_id in ruleset.interaction_set:
        definition = ruleset.cards[card_id]
        card_rows.extend(
            reconcile_card(
                card_id,
                _definition_primitive(definition),
                source_rows.get(card_id),
                tuple(
                    (source_id, _level11_source_rows(payload).get(card_id))
                    for source_id, payload in additional_sources
                ),
            )
        )
    counts: dict[str, int] = {}
    for row in card_rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    unresolved = [
        row
        for row in card_rows
        if row["status"] in {"unresolved_missing_source", "unresolved_source_conflict"}
    ]
    source_hash = (
        source_sha256(source_path)
        if source_path is not None
        else str(source.get("sha256") or source_payload_sha256(source))
    )
    return {
        "schema_version": RECONCILIATION_SCHEMA_VERSION,
        "kind": "simulator_card_data_reconciliation",
        "ruleset_id": ruleset.ruleset_id,
        "ruleset_hash": ruleset.content_hash,
        "level": ruleset.level,
        "source": {
            "source_id": source.get("source_id"),
            "source_url": source.get("source_url"),
            "retrieved_at": source.get("retrieved_at"),
            "confidence_tier": source.get("confidence_tier"),
            "sha256": source_hash,
        },
        "additional_sources": [
            {
                "source_id": source_id,
                "source_url": payload.get("source_url"),
                "retrieved_at": payload.get("retrieved_at"),
                "confidence_tier": payload.get("confidence_tier"),
            }
            for source_id, payload in additional_sources
        ],
        "summary": {
            "card_count": len(ruleset.interaction_set),
            "field_count": len(card_rows),
            "counts_by_status": dict(sorted(counts.items())),
            "unresolved_count": len(unresolved),
            "fully_verified": not unresolved,
            "training_ready": bool(not unresolved and ruleset.metadata.get("training_ready") is True),
        },
        "rows": card_rows,
        "unresolved": unresolved,
    }


def _definition_primitive(definition: Any) -> dict[str, Any]:
    """Extract the fields used by reconciliation from a frozen definition."""

    result = {
        field: getattr(definition, field, None)
        for field in _COMPARE_FIELDS
    }
    result["kind"] = getattr(definition, "kind", None)
    result["mechanics"] = _thaw(getattr(definition, "mechanics", {}))
    return result


def _thaw(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _thaw(child) for key, child in value.items()}
    if isinstance(value, tuple):
        return [_thaw(child) for child in value]
    return value


def report_is_strictly_verified(report: Mapping[str, Any]) -> bool:
    summary = report.get("summary", {})
    return bool(summary.get("fully_verified") and summary.get("training_ready"))


__all__ = [
    "LEVEL11_SOURCE_ID",
    "LEVEL11_SOURCE_PATH",
    "DECKSHOP_SOURCE_PATH",
    "DECKSHOP_CORE_SOURCE_PATH",
    "DECKSHOP_HEAL_SPIRIT_SOURCE_PATH",
    "OFFICIAL_OVERRIDE_PATH",
    "apply_official_overrides",
    "load_level11_source",
    "load_official_overrides",
    "official_override_rows",
    "reconcile_card",
    "reconcile_ruleset",
    "report_is_strictly_verified",
    "source_sha256",
    "source_payload_sha256",
]
