"""Shared constants for the live capture and state-building pipeline."""

NORMAL_SECONDS = 180
OVERTIME_SECONDS = 120
TOTAL_MATCH_SECONDS = NORMAL_SECONDS + OVERTIME_SECONDS

MAX_ELIXIR = 10.0
STARTING_ELIXIR_EST = 6
ELIXIR_PER_SECOND_NORMAL = 1.0 / 2.8
ELIXIR_PER_SECOND_DOUBLE = 1.0 / 1.4
ELIXIR_PER_SECOND_TRIPLE = 1.0 / 0.9

PRINCESS_TOWER_HP = 4424
KING_TOWER_HP = 7032

# The feature encoder currently normalizes king HP against a larger cap than the
# OCR/state path uses. Keep that behavior explicit until you decide to unify it.
FEATURE_MAX_KING_TOWER_HP = 7704.0

FULL_TOWER_HP = {
    "own_king": KING_TOWER_HP,
    "enemy_king": KING_TOWER_HP,
    "own_support_left": PRINCESS_TOWER_HP,
    "own_support_right": PRINCESS_TOWER_HP,
    "enemy_support_left": PRINCESS_TOWER_HP,
    "enemy_support_right": PRINCESS_TOWER_HP,
}

ALLY_CYAN_HSV_LOW = (80, 80, 80)
ALLY_CYAN_HSV_HIGH = (110, 255, 255)


ENEMY_RED_HSV_LOW_1 = (0, 80, 80)
ENEMY_RED_HSV_HIGH_1 = (10, 255, 255)
ENEMY_RED_HSV_LOW_2 = (170, 80, 80)
ENEMY_RED_HSV_HIGH_2 = (179, 255, 255)

OVERTIME_RED_RATIO_THRESHOLD = 0.5
TOWER_BAR_VISIBLE_RATIO_THRESHOLD = 0.3

HAND_CARD_CONFIDENCE_THRESHOLD = 55.0
CARD_CONFIDENCE_THRESHOLD = 45.0
ELIXIR_DIGIT_SCORE_THRESHOLD = 0.45
IN_GAME_SCORE_THRESHOLD = 3
GAME_START_MIN_SECONDS = 170 

YOLO_CONF_THRESHOLD = 0.7
YOLO_IOU_THRESHOLD = 0.6

ENEMY_CARD_CONFIRM_FRAMES = 3
ENEMY_CARD_STALE_AFTER_SECONDS = 2.0
ENEMY_RECENT_CLOCK_CONFIRM_SECONDS = 0.5
ENEMY_RECENT_CLOCK_DUPLICATE_WINDOW_S = 0.75
ENEMY_CLOCK_FIRST_SEEN_MIN_CONF = 0.75
ENEMY_SPELL_OWN_ACTION_VETO_WINDOW_S = 3.0
ENEMY_SPELL_DISTINCT_CELL_DISTANCE = 3
OWN_ACTION_START_TIME_LEFT_S = 294.0
OWN_ACTION_DUPLICATE_WINDOW_S = 3.0
OWN_ACTION_RECENT_HAND_WINDOW_S = 8.0
OWN_ACTION_RECENT_TRACK_WINDOW_S = 1.0
OWN_ACTION_TRACK_AFTER_DROP_WINDOW_S = 5.0
OWN_ACTION_TRACK_FALLBACK_CARDS = {
    "electro-wizard",
}

FRAME_CONFIRM_TROOPS = {
    "electro-wizard",
}

FRAME_CONFIRM_MOVING_SPELLS = {
    "arrows",
    "barbarian-barrel",
    "fireball",
    "giant-snowball",
    "goblin-barrel",
    "rocket",
    "royal-delivery",
    "the-log",
}

FRAME_CONFIRM_STATIONARY_SPELLS = {
    "clone",
    "earthquake",
    "freeze",
    "graveyard",
    "lightning",
    "poison",
    "rage",
    "tornado",
    "zap",
}

FRAME_CONFIRM_CLASSES = (
    FRAME_CONFIRM_TROOPS
    | FRAME_CONFIRM_MOVING_SPELLS
    | FRAME_CONFIRM_STATIONARY_SPELLS
)
