settings_version: 0.0.4
datasets_dir: /home/keschler/Documents/Coding/datasets
weights_dir: /home/keschler/Documents/Coding/cr-bot/weights
runs_dir: /home/keschler/Documents/Coding/cr-bot/runs
uuid: fbcaa2b1edb1544f8ccfd21c1dac77409a9f495d92752baa41fde88098598e42
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
