"""Phase-0 physical differential-testing lab.

The package is intentionally usable without connected hardware.  Use
``offline_runner`` to exercise canonical specs, lifecycle handling, capture
sealing, synchronization, and deterministic simulator replay.  ADB adapters
are available for a later connected-device session and fail closed when a
phone is absent.
"""

from .calibration import CalibrationArtifact, CalibrationError
from .automation import (
    AutonomousPhysicalLab,
    AutonomousPhone,
    AutonomousSessionConfig,
    AutomationError,
    CardMatch,
    CardVision,
    DEFAULT_FRIENDLY_TARGET_PLAYER_NAME,
    FIXED_DECK_LONG_PRESS_MS,
    FIXED_HOG_CYCLE_DECK,
    FIXED_HOG_CYCLE_OPENING_HAND,
    FIXED_HOG_CYCLE_REPLACEMENT_ORDER,
    SAMSUNG_HERO_MUSKETEER_MODEL_IDS,
    SAMSUNG_SPECIAL_CARD_FIRST_THREE_IDS,
    SAMSUNG_REGULAR_MUSKETEER_HUMAN_SLOT_RANGE,
    SAMSUNG_REGULAR_MUSKETEER_MIN_SLOT,
    SAMSUNG_COLLECTION_IDENTITY_MIN_SCORES,
    ASUS_REGULAR_MUSKETEER_MODEL_IDS,
    ASUS_REGULAR_MUSKETEER_MIN_SLOT,
    ASUS_REGULAR_MUSKETEER_HUMAN_SLOT_RANGE,
    MUSKETEER_COLLECTION_CANDIDATE_MIN_SCORE,
    ASUS_COLLECTION_CANDIDATE_MIN_SCORES,
    ASUS_COLLECTION_IDENTITY_MIN_SCORES,
    UiProfile,
    bind_spec_to_devices,
)
from .artifacts import finalize_retention_records
from .cache import ReplayCacheError, ReplayCacheSeal, seal_replay_cache
from .campaign import (
    CAMPAIGN_LEVELS,
    CAMPAIGN_SCHEMA_VERSION,
    CampaignCase,
    DeckMutation,
    InteractionCampaign,
    PHONE_A_CARD_CONSTRAINTS,
    PHONE_A_REGULAR_MUSKETEER_DECK,
    PHONE_B_CARD_CONSTRAINTS,
    PHONE_B_REGULAR_MUSKETEER_DECK,
    apply_deck_mutations,
    build_default_campaign,
    evaluate_campaign,
    load_campaign,
    materialize_campaign,
    write_campaign_evaluation,
)
from .comparison import ComparisonReport, compare_observation_to_replay
from .fidelity_bridge import build_fidelity_corpus_payload, write_fidelity_corpus_payload
from .policy_bridge import (
    PlacementCommand,
    PolicyBridgeError,
    dispatch_policy_action,
    observation_from_game_state,
    observation_from_match_step,
    observation_v2_from_game_state,
    observation_v2_from_match_step,
    placement_command_from_policy_action,
)
from .extraction import (
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_JOB_TIMEOUT_S,
    DEFAULT_SAMPLE_INTERVAL_S,
    EXTRACTION_SCHEMA_VERSION,
    ExtractorJobResult,
    PhysicalExtractionError,
    extract_physical_run,
)
from .evaluation import (
    EVALUATION_SCHEMA_VERSION,
    evaluate_stored_cases,
    write_stored_evaluation,
)
from .devices import (
    ActionReceipt,
    AdbPhoneController,
    AdbScreenCapture,
    CaptureHandle,
    CaptureManifest,
    DeviceDisconnectedError,
    DeviceCommandError,
    DeviceInfo,
    FakePhoneController,
    FakeScreenCapture,
    FrameBufferCapture,
    Frame,
    LogicalPhone,
    PhoneController,
    ScreenCapture,
    ScrcpyScreenCapture,
    monotonic_time_us,
)
from .lifecycle import (
    LIFECYCLE_PATH,
    LifecycleFailure,
    LifecycleMachine,
    LifecyclePolicy,
    LifecycleReport,
    LifecycleState,
    LifecycleTransition,
    ScriptedLifecycleDetector,
)
from .screen_state import (
    SCREEN_TEMPLATE_SCHEMA_VERSION,
    ScreenStateDetectionError,
    TemplateLifecycleDetector,
)
from .observation import (
    EntityObservation,
    EntitySample,
    NormalizedEvent,
    ObservationCertainty,
    ObservationManifest,
    RejectedObservation,
    ingest_extracted_observations,
)
from .observation_waiter import (
    HogBridgeObservationWaiter,
    LiveTrackObservationSource,
    TrackObservation,
)
from .planner import (
    PlannedExperiment,
    PriorityInputs,
    hog_cannon_probe,
    plan_from_questions,
    plan_from_readiness,
)
from .replay import ReplayAction, SimulatorReplay, build_scenario, run_simulator_replay
from .runner import (
    ActionLogEntry,
    ClockProvenance,
    PhysicalLabRunner,
    PhysicalRunResult,
    offline_runner,
    write_run_artifacts,
)
from .schema import (
    DeviceSpec,
    EvidenceSplit,
    EvidenceStatus,
    ExperimentSpec,
    InitialConditions,
    MeasurementSpec,
    PhysicalAction,
    PhysicalLabError,
    Trigger,
    TriggerType,
)
from .sync import (
    DeviceClockAlignment,
    SynchronizationError,
    SynchronizationResult,
    SyncMarker,
    TimeMapping,
    estimate_clock_alignment,
)
from .split import SPLIT_LOCK_SCHEMA_VERSION, SplitLock, assign_capture_group_split


__all__ = [
    "ActionLogEntry",
    "ClockProvenance",
    "ActionReceipt",
    "AdbPhoneController",
    "AdbScreenCapture",
    "AutonomousPhysicalLab",
    "AutonomousPhone",
    "AutonomousSessionConfig",
    "AutomationError",
    "CalibrationArtifact",
    "CalibrationError",
    "CAMPAIGN_LEVELS",
    "CAMPAIGN_SCHEMA_VERSION",
    "CampaignCase",
    "DeckMutation",
    "InteractionCampaign",
    "ReplayCacheError",
    "ReplayCacheSeal",
    "CaptureHandle",
    "CaptureManifest",
    "CardMatch",
    "CardVision",
    "DEFAULT_FRIENDLY_TARGET_PLAYER_NAME",
    "FIXED_DECK_LONG_PRESS_MS",
    "ComparisonReport",
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "DEFAULT_JOB_TIMEOUT_S",
    "DEFAULT_SAMPLE_INTERVAL_S",
    "DeviceClockAlignment",
    "DeviceDisconnectedError",
    "DeviceCommandError",
    "DeviceInfo",
    "DeviceSpec",
    "EntityObservation",
    "EntitySample",
    "EXTRACTION_SCHEMA_VERSION",
    "EVALUATION_SCHEMA_VERSION",
    "EvidenceSplit",
    "EvidenceStatus",
    "ExperimentSpec",
    "FakePhoneController",
    "FakeScreenCapture",
    "FrameBufferCapture",
    "Frame",
    "FIXED_HOG_CYCLE_DECK",
    "FIXED_HOG_CYCLE_OPENING_HAND",
    "FIXED_HOG_CYCLE_REPLACEMENT_ORDER",
    "InitialConditions",
    "LIFECYCLE_PATH",
    "LifecycleFailure",
    "LifecycleMachine",
    "LifecyclePolicy",
    "LifecycleReport",
    "LifecycleState",
    "LifecycleTransition",
    "LiveTrackObservationSource",
    "LogicalPhone",
    "MeasurementSpec",
    "NormalizedEvent",
    "ObservationCertainty",
    "ObservationManifest",
    "PhoneController",
    "PhysicalAction",
    "PhysicalLabError",
    "PhysicalExtractionError",
    "PlacementCommand",
    "PolicyBridgeError",
    "PhysicalLabRunner",
    "PhysicalRunResult",
    "ExtractorJobResult",
    "PHONE_B_CARD_CONSTRAINTS",
    "PHONE_B_REGULAR_MUSKETEER_DECK",
    "PHONE_A_CARD_CONSTRAINTS",
    "PHONE_A_REGULAR_MUSKETEER_DECK",
    "SAMSUNG_HERO_MUSKETEER_MODEL_IDS",
    "SAMSUNG_SPECIAL_CARD_FIRST_THREE_IDS",
    "SAMSUNG_REGULAR_MUSKETEER_HUMAN_SLOT_RANGE",
    "SAMSUNG_REGULAR_MUSKETEER_MIN_SLOT",
    "SAMSUNG_COLLECTION_IDENTITY_MIN_SCORES",
    "ASUS_REGULAR_MUSKETEER_MODEL_IDS",
    "ASUS_REGULAR_MUSKETEER_MIN_SLOT",
    "ASUS_REGULAR_MUSKETEER_HUMAN_SLOT_RANGE",
    "MUSKETEER_COLLECTION_CANDIDATE_MIN_SCORE",
    "ASUS_COLLECTION_CANDIDATE_MIN_SCORES",
    "ASUS_COLLECTION_IDENTITY_MIN_SCORES",
    "PlannedExperiment",
    "PriorityInputs",
    "RejectedObservation",
    "ReplayAction",
    "ScriptedLifecycleDetector",
    "SCREEN_TEMPLATE_SCHEMA_VERSION",
    "ScreenStateDetectionError",
    "TemplateLifecycleDetector",
    "SPLIT_LOCK_SCHEMA_VERSION",
    "ScreenCapture",
    "ScrcpyScreenCapture",
    "SplitLock",
    "SimulatorReplay",
    "SynchronizationError",
    "SynchronizationResult",
    "SyncMarker",
    "TimeMapping",
    "TrackObservation",
    "Trigger",
    "TriggerType",
    "UiProfile",
    "bind_spec_to_devices",
    "build_scenario",
    "build_fidelity_corpus_payload",
    "compare_observation_to_replay",
    "estimate_clock_alignment",
    "extract_physical_run",
    "evaluate_stored_cases",
    "write_stored_evaluation",
    "finalize_retention_records",
    "assign_capture_group_split",
    "apply_deck_mutations",
    "build_default_campaign",
    "evaluate_campaign",
    "hog_cannon_probe",
    "HogBridgeObservationWaiter",
    "ingest_extracted_observations",
    "offline_runner",
    "monotonic_time_us",
    "load_campaign",
    "materialize_campaign",
    "plan_from_questions",
    "plan_from_readiness",
    "run_simulator_replay",
    "seal_replay_cache",
    "write_run_artifacts",
    "write_fidelity_corpus_payload",
    "dispatch_policy_action",
    "observation_from_game_state",
    "observation_from_match_step",
    "observation_v2_from_game_state",
    "observation_v2_from_match_step",
    "placement_command_from_policy_action",
    "write_campaign_evaluation",
]
