"""Real-simulator timing curriculum for V4 Stage 1 (2.6 Hog WAIT/PLAY timing).

The natural simulator distribution is ~96.6% PLAY, so mode/duration heads
are never meaningfully tested.  This module builds a dedicated *balanced*
timing dataset from short temporal sequences generated by real simulator
rollouts, labeled by the timing teacher (:mod:`rl.timing_teacher`).

Design rules (enforced, not aspirational):

* Every elixir/threat/hand modification happens in authoritative simulator
  state FIRST; observations are regenerated afterwards via
  ``observe_v2_for_viewer``, so elixir scalar, raster, entities, hand, and
  legal masks stay internally consistent.  Public feature vectors are never
  patched directly.
* WAITs are strategic (rich elixir, legal PLAYs available, wrong moment),
  not broke states.  The quota balancer caps WAITs without legal PLAY.
* Sequences cross one teacher decision boundary (elixir affordability,
  threat-distance window, match clock), producing WAIT* -> PLAY switches
  from the same rollout: ``3.5 -> WAIT, 3.9 -> WAIT, 4.0 -> PLAY Hog``.
* Everything is deterministic per ``(seed, family, sequence)``: fresh
  environments, hash-derived setpoints, frozen WAIT-only opponent.

Six timing families (2.6 Hog, fixed player deck):

* ``opening-scout``: match start, 9-10 elixir, brief scouting hold (T1).
* ``preserve-defense``: ground threat, Cannon in hand but unaffordable
  while cheap is playable; WAIT for Cannon (T5).  Includes unanswerable-air
  variants (rich, wrong answers) for high-elixir WAIT coverage.
* ``counterpush-save``: surviving Musketeer, quiet board, Hog in hand but
  unaffordable; WAIT until Hog is affordable, then counterpush (T3/T4).
* ``defensive-timing``: Cannon affordable, threat still outside the
  placement window; WAIT until it enters (T2).  Elixir held sufficient so
  timing depends on position, not affordability.
* ``hold-utility``: spells affordable but low-value (dispersed targets);
  WAIT until a cluster is worth the Fireball/Log, or until elixir crosses a
  spell-affordability boundary into a clustered state.
* ``avoid-overcommit``: own Hog pushing, elixir below the cycle threshold;
  WAIT instead of adding support (T4), sometimes ending in defense when a
  threat arrives.

Consumers see ``DistillationSample`` + ``to_torch_batch`` unchanged; timing
metadata (family, sequence id/offset, legal-card counts, teacher duration)
travels in ``provenance``.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from typing import Any, Callable, Sequence

import numpy as np

try:
    from ..ruleset import load_fixed_ruleset
    from ..roster import PLAYER_DECK as ROSTER_PLAYER_DECK
    from .basic_scenarios import BasicMechanicsScenarioEnv, BasicScenarioConfig
    from .distillation import DistillationSample
    from .opponent_pool import OpponentPool
    from .simulator_distillation import build_hand_tokens
    from .simulator_teacher import TeacherError, soft_placement_target
    from .timing_teacher import TIMING_TEACHER_VERSION, timing_teacher_label
except ImportError:  # pragma: no cover - top-level ``rl`` imports
    from simulator.ruleset import load_fixed_ruleset
    from simulator.roster import PLAYER_DECK as ROSTER_PLAYER_DECK
    from simulator.rl.basic_scenarios import BasicMechanicsScenarioEnv, BasicScenarioConfig
    from simulator.rl.distillation import DistillationSample
    from simulator.rl.opponent_pool import OpponentPool
    from simulator.rl.simulator_distillation import build_hand_tokens
    from simulator.rl.simulator_teacher import TeacherError, soft_placement_target
    from simulator.rl.timing_teacher import TIMING_TEACHER_VERSION, timing_teacher_label


TIMING_GENERATOR_VERSION: str = "timing-v4-0"

TIMING_FAMILIES: tuple[str, ...] = (
    "opening-scout",
    "preserve-defense",
    "counterpush-save",
    "defensive-timing",
    "hold-utility",
    "avoid-overcommit",
)

_DEFAULT_FAMILY_WEIGHTS: dict[str, float] = {
    "opening-scout": 0.24,
    "preserve-defense": 0.17,
    "counterpush-save": 0.14,
    "defensive-timing": 0.17,
    "hold-utility": 0.14,
    "avoid-overcommit": 0.14,
}

# Opponent archetype per family (mirrors the basic-scenario contract).
_FAMILY_ARCHETYPE: dict[str, str] = {
    "opening-scout": "aggressive-pressure",
    "preserve-defense": "beatdown",
    "counterpush-save": "aggressive-pressure",
    "defensive-timing": "beatdown",
    "hold-utility": "siege-bait",
    "avoid-overcommit": "aggressive-pressure",
}

# Fixed-deck costs (milli) for elixir setpoints; must match the hand builder.
_HOG_COST = 4_000
_CANNON_COST = 3_000
_LOG_COST = 2_000

_Y_HOLD = 0.60
_SCOUT_SECONDS = 0.75
_MAX_SEQ_STEPS = 10


def _stable_seed(seed: int, *parts: object) -> int:
    payload = "\x1f".join((str(seed), *(str(part) for part in parts))).encode()
    return int.from_bytes(hashlib.sha256(payload).digest()[:8], "big")


@dataclass(frozen=True, slots=True)
class TimingConfig:
    """Target size and balance contract for the timing dataset."""

    n_states: int
    seed: int
    family_weights: dict[str, float] | None = None
    pool_factor: int = 3
    mode_target: float = 0.5
    mode_tol: float = 0.03
    family_min_share: float = 0.10
    duration_min: float = 0.15
    duration_max: float = 0.40
    max_wait_without_play_share: float = 0.30

    def __post_init__(self) -> None:
        if type(self.n_states) is not int or self.n_states <= 0:
            raise ValueError("n_states must be a positive integer")
        if type(self.seed) is not int or self.seed < 0:
            raise ValueError("seed must be a non-negative integer")
        weights = dict(_DEFAULT_FAMILY_WEIGHTS) if self.family_weights is None else dict(self.family_weights)
        if set(weights) != set(TIMING_FAMILIES):
            raise ValueError(f"family_weights must cover exactly {TIMING_FAMILIES}")
        if any(not isinstance(w, float) or w <= 0.0 for w in weights.values()):
            raise ValueError("family_weights values must be positive floats")
        object.__setattr__(self, "family_weights", weights)
        if type(self.pool_factor) is not int or self.pool_factor < 1:
            raise ValueError("pool_factor must be a positive integer")


@dataclass
class _TimingContext:
    """Shared read-only simulator state for one timing-generation run."""

    ruleset: Any
    pool: OpponentPool
    tick_us: int

    @classmethod
    def build(cls, seed: int) -> "_TimingContext":
        ruleset = load_fixed_ruleset()
        return cls(ruleset=ruleset, pool=OpponentPool(ruleset, seed=seed), tick_us=int(ruleset.tick_us))


# ---------------------------------------------------------------------------
# Authoritative-state construction helpers.
#
# Everything here mutates BattleState BEFORE any observation is built, so all
# derived tensors stay consistent.  Nothing patches feature vectors.
# ---------------------------------------------------------------------------


def _set_hand(state: Any, player: int, keys: tuple[str, ...] | list[str]) -> None:
    """Arrange the player's hand deterministically (deck stays consistent)."""

    keys = list(keys)
    if len(keys) != 4 or len(set(keys)) != 4:
        raise TeacherError("timing hand must hold four distinct cards")
    player_state = state.players[player]
    if any(card not in player_state.deck for card in keys):
        raise TeacherError(f"timing hand {keys} outside the player deck")
    rest = [card for card in player_state.deck if card not in keys]
    player_state.hand = list(keys)
    player_state.draw_pile = rest
    player_state.next_card_cooldown_us = 0


def _set_elixir(state: Any, player: int, milli: int) -> None:
    if milli < 0 or milli > 10_000:
        raise TeacherError(f"elixir setpoint {milli} out of range")
    player_state = state.players[player]
    player_state.elixir_milli = int(milli)
    player_state.elixir_remainder = 0


def _pick_cell(cells: Any, col: int, row: int) -> tuple[int, int]:
    if not cells:
        raise TeacherError("no legal deployment cell for setup card")
    return min(
        cells,
        key=lambda cell: (abs(cell[0] - col) + abs(cell[1] - row), cell[1], cell[0]),
    )


def _deploy(
    context: _TimingContext,
    state: Any,
    engine: Any,
    player: int,
    card: str,
    col: int,
    row: int,
) -> None:
    """Deploy one setup card through the authoritative action path."""

    try:
        from ..actions import PlayCardAction
    except ImportError:  # pragma: no cover - top-level ``rl`` imports
        from simulator.actions import PlayCardAction
    player_state = state.players[player]
    if card not in player_state.deck:
        raise TeacherError(f"setup card {card!r} absent from the deck")
    player_state.elixir_milli = 10_000
    player_state.elixir_remainder = 0
    player_state.next_card_cooldown_us = 0
    hand = list(player_state.hand)
    if card in hand:
        slot = hand.index(card)
    else:
        draw_index = player_state.draw_pile.index(card)
        slot = 0
        player_state.hand[slot], player_state.draw_pile[draw_index] = (
            player_state.draw_pile[draw_index],
            player_state.hand[slot],
        )
    cell = _pick_cell(engine.legal_cells(state, player, card), col, row)
    result = engine.apply_actions(state, (PlayCardAction(player, slot, cell),))
    if len(result) != 1 or not result[0].accepted:
        raise TeacherError(f"setup deploy of {card!r} rejected: {result[0].reason if result else None}")
    state.players[0].next_card_cooldown_us = 0
    state.players[1].next_card_cooldown_us = 0


def _live_enemies(state: Any, owner: int = 1) -> list[Any]:
    return [
        entity
        for entity in state.entities.values()
        if entity.alive and entity.owner == owner and entity.kind != "tower"
    ]


def _live_own_troops(state: Any) -> list[Any]:
    return [
        entity
        for entity in state.entities.values()
        if entity.alive and entity.owner == 0 and entity.kind != "tower"
    ]


def _is_building_entity(context: _TimingContext, entity: Any) -> bool:
    card_id = getattr(entity, "card_id", "")
    try:
        definition = context.ruleset.card(card_id)
    except (KeyError, ValueError):
        return False
    return str(getattr(definition, "kind", "")) == "building"


def _live_own_musk_or_troop(state: Any, context: _TimingContext) -> list[Any]:
    return [e for e in _live_own_troops(state) if not _is_building_entity(context, e)]


# ---------------------------------------------------------------------------
# Environment scaffolding: wrapped scenarios or raw env, WAIT-stepped.
# ---------------------------------------------------------------------------


def _new_wrapped_env(context: _TimingContext, source: str, opponent_cards: tuple[str, ...], seed: int) -> Any:
    try:
        from ..engine import BattleEngine
        from ..env import SimulatorEnv
    except ImportError:  # pragma: no cover - top-level ``rl`` imports
        from simulator.engine import BattleEngine
        from simulator.env import SimulatorEnv
    base = SimulatorEnv(
        engine=BattleEngine(context.ruleset, validate_every_tick=False),
        decision_interval_us=250_000,
    )
    wrapped = BasicMechanicsScenarioEnv(
        base,
        BasicScenarioConfig(source=source, target_player=0, decision_limit=64),
    )
    wrapped.reset_v2(
        seed=seed,
        decks=(tuple(ROSTER_PLAYER_DECK), tuple(opponent_cards)),
        shuffle_decks=True,
    )
    return wrapped


def _new_raw_env(context: _TimingContext, opponent_cards: tuple[str, ...], seed: int) -> Any:
    try:
        from ..engine import BattleEngine
        from ..env import SimulatorEnv
    except ImportError:  # pragma: no cover - top-level ``rl`` imports
        from simulator.engine import BattleEngine
        from simulator.env import SimulatorEnv
    env = SimulatorEnv(
        engine=BattleEngine(context.ruleset, validate_every_tick=False),
        decision_interval_us=250_000,
    )
    env.reset_v2(
        seed=seed,
        decks=(tuple(ROSTER_PLAYER_DECK), tuple(opponent_cards)),
        shuffle_decks=True,
    )
    return env


def _step_wait(env: Any) -> None:
    try:
        from ..actions import WaitAction
    except ImportError:  # pragma: no cover - top-level ``rl`` imports
        from simulator.actions import WaitAction
    env.step_v2((WaitAction(0), WaitAction(1)))


# ---------------------------------------------------------------------------
# Capture + label.
# ---------------------------------------------------------------------------


def _capture(
    context: _TimingContext,
    env: Any,
    *,
    family: str,
    seq_id: str,
    offset: int,
    env_seed: int,
    source: str,
) -> dict[str, Any] | None:
    """Observe, label, and package one decision point (None if unusable)."""

    state = env.state
    if state is None or state.terminal:
        return None
    try:
        observation = env.observe_v2_for_viewer(0)
    except (ValueError, TypeError):
        return None
    player_state = state.players[0]
    hand = list(player_state.hand)
    if len(hand) != 4:
        return None
    elixir = float(player_state.elixir_milli) / 1000.0
    try:
        hand_tokens = build_hand_tokens(hand, elixir)
    except TeacherError:
        return None
    legal_play = np.array(observation.legal_play, dtype=bool)
    tick_seconds = float(state.tick) * float(context.tick_us) / 1_000_000.0
    try:
        target = timing_teacher_label(
            hand_tokens=hand_tokens,
            entity_tokens=np.asarray(observation.entity_tokens),
            entity_mask=np.asarray(observation.entity_mask),
            legal_play=legal_play,
            legal_wait=bool(observation.legal_wait),
            own_elixir=elixir,
            tick_seconds=tick_seconds,
            y_hold=_Y_HOLD,
            scout_seconds=_SCOUT_SECONDS,
        )
    except TeacherError:
        return None
    if target.mode == 1:
        try:
            soft = soft_placement_target(
                target.row, target.col, np.asarray(legal_play[target.card_slot])
            )
        except TeacherError:
            return None
    else:
        soft = np.zeros((32, 18), dtype=np.float32)
    legal_cards = int(np.asarray(legal_play).reshape(4, -1).any(axis=1).sum())
    return {
        "family": family,
        "raster": np.array(observation.board, dtype=np.float32),
        "global_features": np.array(observation.global_vector, dtype=np.float32),
        "entity_tokens": np.array(observation.entity_tokens, dtype=np.float32),
        "entity_mask": np.array(observation.entity_mask, dtype=bool),
        "hand_tokens": hand_tokens,
        "legal_play": legal_play,
        "legal_wait": bool(observation.legal_wait),
        "own_elixir": float(elixir),
        "target": target,
        "soft_placement": soft,
        "mode": int(target.mode),
        "duration": int(target.wait_duration_idx),
        "card_slot": int(target.card_slot),
        "seq_id": seq_id,
        "offset": int(offset),
        "legal_cards": legal_cards,
        "play_legal": bool(legal_cards > 0),
        "provenance": {
            "generator": TIMING_GENERATOR_VERSION,
            "teacher": TIMING_TEACHER_VERSION,
            "timing_family": family,
            "seq_id": seq_id,
            "sequence_offset": int(offset),
            "env_seed": int(env_seed),
            "state_hash": state.state_hash(),
            "source": source,
            "target_elixir_milli": int(player_state.elixir_milli),
            "target_hand": list(hand),
            "legal_cards": legal_cards,
            "teacher_mode": int(target.mode),
            "teacher_card_slot": int(target.card_slot),
            "teacher_wait_duration": int(target.wait_duration_idx),
            "play_legal_during_wait": bool(legal_cards > 0),
            "tick_seconds": round(tick_seconds, 3),
        },
    }


# ---------------------------------------------------------------------------
# Six family constructors.  Each returns a list of capture dicts (possibly
# empty when postconditions fail); all randomness derives from seeds.
# ---------------------------------------------------------------------------


def _build_opening(
    context: _TimingContext, config: TimingConfig, seq_idx: int,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    env_seed = _stable_seed(config.seed, "timing", "opening-scout", seq_idx)
    env = _new_raw_env(context, tuple(ROSTER_PLAYER_DECK), env_seed)
    elixir = 9000 + (env_seed % 3) * 500
    _set_elixir(env.state, 0, elixir)
    seq_id = f"opening-scout:{seq_idx}"
    captures: list[dict[str, Any]] = []
    for offset in range(4):
        record = _capture(
            context, env, family="opening-scout", seq_id=seq_id,
            offset=offset, env_seed=env_seed, source="raw-opening",
        )
        if record is None:
            break
        captures.append(record)
        if live_hook is not None:
            live_hook(env, record, offset)
        _step_wait(env)
    return captures


def _build_preserve(
    context: _TimingContext, config: TimingConfig, seq_idx: int,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    env_seed = _stable_seed(config.seed, "timing", "preserve-defense", seq_idx)
    variant = (env_seed % 4 == 3)  # ~25%: unanswerable-air, rich WAITs
    source = "air-defense" if variant else "ground-defense"
    archetype = _FAMILY_ARCHETYPE["preserve-defense"] if not variant else "air-beatdown"
    opponent = context.pool.sample(seq_idx, archetype=archetype, strategy="deterministic-cycle")
    env = _new_wrapped_env(context, source, opponent.deck.cards, env_seed)
    state, engine = env.state, env.engine
    if variant:
        _set_hand(state, 0, ["hog-rider", "cannon", "skeletons", "ice-golem"])
        if seq_idx % 8 == 3:
            # Upper half of variants sit at 8-10k elixir, the only natural
            # source of duration-0 WAITs besides the opening family.
            _set_elixir(state, 0, 8000 + env_seed % 2001)
        else:
            _set_elixir(state, 0, 6000 + env_seed % 2001)
    else:
        _set_hand(state, 0, ["cannon", "skeletons", "hog-rider", "musketeer"])
        _set_elixir(state, 0, 2400 + env_seed % 500)
    engine.validate_state(state)
    seq_id = f"preserve-defense:{seq_idx}"
    captures: list[dict[str, Any]] = []
    for offset in range(_MAX_SEQ_STEPS):
        if not _live_enemies(state):
            break
        record = _capture(
            context, env, family="preserve-defense", seq_id=seq_id,
            offset=offset, env_seed=env_seed, source=source,
        )
        if record is None:
            break
        captures.append(record)
        if live_hook is not None:
            live_hook(env, record, offset)
        _step_wait(env)
        if env.state is None or env.state.terminal:
            break
        state = env.state
    return captures


def _build_counterpush(
    context: _TimingContext, config: TimingConfig, seq_idx: int,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    env_seed = _stable_seed(config.seed, "timing", "counterpush-save", seq_idx)
    opponent = context.pool.sample(
        seq_idx, archetype=_FAMILY_ARCHETYPE["counterpush-save"], strategy="deterministic-cycle"
    )
    env = _new_wrapped_env(context, "isolated-offense", opponent.deck.cards, env_seed)
    state, engine = env.state, env.engine
    lane_col = 3 if env_seed % 2 == 0 else 14
    _deploy(context, state, engine, 0, "musketeer", lane_col, 25 + env_seed % 3)
    _set_hand(state, 0, ["hog-rider", "skeletons", "ice-spirit", "ice-golem"])
    _set_elixir(state, 0, 3400 + env_seed % 500)
    engine.validate_state(state)
    seq_id = f"counterpush-save:{seq_idx}"
    captures: list[dict[str, Any]] = []
    for offset in range(_MAX_SEQ_STEPS):
        if _live_enemies(state) or not _live_own_musk_or_troop(state, context):
            break
        record = _capture(
            context, env, family="counterpush-save", seq_id=seq_id,
            offset=offset, env_seed=env_seed, source="isolated-offense",
        )
        if record is None:
            break
        captures.append(record)
        if live_hook is not None:
            live_hook(env, record, offset)
        if record["mode"] == 1:
            break  # counterpush committed; further states leave the pattern
        _step_wait(env)
        if env.state is None or env.state.terminal:
            break
        state = env.state
    return captures


def _build_defensive_timing(
    context: _TimingContext, config: TimingConfig, seq_idx: int,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    env_seed = _stable_seed(config.seed, "timing", "defensive-timing", seq_idx)
    opponent = context.pool.sample(
        seq_idx, archetype=_FAMILY_ARCHETYPE["defensive-timing"], strategy="deterministic-cycle"
    )
    seq_id = f"defensive-timing:{seq_idx}"
    captures: list[dict[str, Any]] = []
    if seq_idx % 2 == 0:
        # Scenario threat: prelude-advanced, often already near the window.
        env = _new_wrapped_env(context, "ground-defense", opponent.deck.cards, env_seed)
        state, engine = env.state, env.engine
        source = "ground-defense"
    else:
        # Custom far threat: tankiest ground troop deployed deep, so the
        # capture arc spans pre-threat -> hold -> placement window.
        ground = sorted(
            _ground_troops(context, tuple(opponent.deck.cards)),
            key=lambda card: (-_card_cost(context, card), card),
        )
        if not ground:
            return []
        env = _new_raw_env(context, tuple(opponent.deck.cards), env_seed)
        state, engine = env.state, env.engine
        _deploy(context, state, engine, 1, ground[0], 9, 8 + env_seed % 4)
        source = "raw-far-threat"
    _set_hand(state, 0, ["cannon", "musketeer", "fireball", "log"])
    _set_elixir(state, 0, 6000 + env_seed % 1001)
    engine.validate_state(state)
    for offset in range(_MAX_SEQ_STEPS):
        foes = [e for e in _live_enemies(state)]
        ground = [e for e in foes if not _is_air_entity(context, e)]
        if not ground:
            break
        record = _capture(
            context, env, family="defensive-timing", seq_id=seq_id,
            offset=offset, env_seed=env_seed, source=source,
        )
        if record is None:
            break
        captures.append(record)
        if live_hook is not None:
            live_hook(env, record, offset)
        _step_wait(env)
        if env.state is None or env.state.terminal:
            break
        state = env.state
    return captures


def _ground_troops(context: _TimingContext, deck: tuple[str, ...]) -> list[str]:
    return [
        card for card in _troop_cards(context, deck)
        if not _is_air_card(context, card)
    ]


def _card_cost(context: _TimingContext, card_id: str) -> int:
    try:
        return int(context.ruleset.card(card_id).elixir_milli)
    except (KeyError, ValueError, AttributeError):
        return 0


def _spawn_count(context: _TimingContext, card_id: str) -> int:
    try:
        return int(context.ruleset.card(card_id).spawn_count or 1)
    except (KeyError, ValueError, AttributeError):
        return 1


def _is_air_card(context: _TimingContext, card_id: str) -> bool:
    try:
        definition = context.ruleset.card(card_id)
    except (KeyError, ValueError):
        return False
    mechanics = getattr(definition, "mechanics", {}) or {}
    get = getattr(mechanics, "get", None)
    layer = get("movement_layer") if callable(get) else None
    if layer is not None:
        return str(layer) == "air"
    return bool(getattr(definition, "is_air", False))


def _is_air_entity(context: _TimingContext, entity: Any) -> bool:
    return _is_air_card(context, str(getattr(entity, "card_id", "")))


def _troop_cards(context: _TimingContext, deck: tuple[str, ...]) -> list[str]:
    troops = []
    for card_id in deck:
        try:
            definition = context.ruleset.card(card_id)
        except (KeyError, ValueError):
            continue
        if str(getattr(definition, "kind", "")) == "troop":
            troops.append(card_id)
    return troops


def _build_hold_utility(
    context: _TimingContext, config: TimingConfig, seq_idx: int,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    env_seed = _stable_seed(config.seed, "timing", "hold-utility", seq_idx)
    seq_id = f"hold-utility:{seq_idx}"
    captures: list[dict[str, Any]] = []
    if env_seed % 2 == 0:
        # Dispersed WAITs: two bodies deployed far apart and far back, so no
        # threat and no cluster exists; elixir is mid and Hog is out of hand,
        # so holding (including spell ammo) is correct.  As they walk into
        # threat range the arc ends in defense PLAYs.
        opponent = context.pool.sample(
            seq_idx, archetype=_FAMILY_ARCHETYPE["hold-utility"], strategy="deterministic-cycle"
        )
        troops = _troop_cards(context, tuple(opponent.deck.cards))
        if len(troops) < 2:
            return []
        env = _new_raw_env(context, tuple(opponent.deck.cards), env_seed)
        state, engine = env.state, env.engine
        _deploy(context, state, engine, 1, troops[0], 6, 4)
        _deploy(context, state, engine, 1, troops[1], 12, 9)
        _set_hand(state, 0, ["fireball", "log", "cannon", "musketeer"])
        _set_elixir(state, 0, 4000 + env_seed % 2001)
        engine.validate_state(state)
        source = "raw-dispersed"
        for offset in range(_MAX_SEQ_STEPS):
            if len(_live_enemies(state)) < 2:
                break
            record = _capture(
                context, env, family="hold-utility", seq_id=seq_id,
                offset=offset, env_seed=env_seed, source=source,
            )
            if record is None:
                break
            captures.append(record)
            if live_hook is not None:
                live_hook(env, record, offset)
            _step_wait(env)
            if env.state is None or env.state.terminal:
                break
            state = env.state
    else:
        # Clustered spell PLAYs: adjacent bodies, no threats, elixir ramps
        # into spell affordability (log at 2.0, fireball below 6.0).
        opponent = context.pool.sample(
            seq_idx, archetype=_FAMILY_ARCHETYPE["hold-utility"], strategy="deterministic-cycle"
        )
        log_play = env_seed % 4 < 2
        troops = _troop_cards(context, tuple(opponent.deck.cards))
        if log_play:
            # Log is a restricted spell (own half only) that cannot hit air.
            # Static pair just off the bridge: threats (y > 0.45) with no
            # affordable non-spell answer, so the spell rule answers Log.
            # (Pairs deployed exactly on the bridge row do not path; the
            # frozen stack is discarded in favor of row 13.)
            troops = sorted(
                troops,
                key=lambda card: (
                    _spawn_count(context, card) != 1,
                    _is_air_card(context, card),
                    -_card_cost(context, card),
                    card,
                ),
            )
            base_row = 13
        else:
            troops = sorted(troops, key=lambda card: (_spawn_count(context, card) != 1, card))
            base_row = 6 + env_seed % 5
        if len(troops) < 2:
            return []
        env = _new_raw_env(context, tuple(opponent.deck.cards), env_seed)
        state, engine = env.state, env.engine
        for card in troops[:2]:
            _deploy(context, state, engine, 1, card, 9, base_row)
        if log_play:
            _set_hand(state, 0, ["log", "hog-rider", "musketeer", "cannon"])
            _set_elixir(state, 0, 2000 + env_seed % 500)
        else:
            _set_hand(state, 0, ["fireball", "log", "hog-rider", "musketeer"])
            _set_elixir(state, 0, 3900 + env_seed % 100)
        engine.validate_state(state)
        for offset in range(10):
            if len(_live_enemies(state)) < 2:
                break
            record = _capture(
                context, env, family="hold-utility", seq_id=seq_id,
                offset=offset, env_seed=env_seed, source="raw-cluster",
            )
            if record is None:
                break
            captures.append(record)
            if live_hook is not None:
                live_hook(env, record, offset)
            if record["mode"] == 1:
                break
            _step_wait(env)
            if env.state is None or env.state.terminal:
                break
            state = env.state
    return captures


def _build_avoid_overcommit(
    context: _TimingContext, config: TimingConfig, seq_idx: int,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    env_seed = _stable_seed(config.seed, "timing", "avoid-overcommit", seq_idx)
    variant = seq_idx % 3 == 2  # threat-arrival variant ends in defense
    source = "ground-defense" if variant else "isolated-offense"
    opponent = context.pool.sample(
        seq_idx, archetype=_FAMILY_ARCHETYPE["avoid-overcommit"], strategy="deterministic-cycle"
    )
    env = _new_wrapped_env(context, source, opponent.deck.cards, env_seed)
    state, engine = env.state, env.engine
    lane_col = 4 if env_seed % 2 == 0 else 13
    _deploy(context, state, engine, 0, "hog-rider", lane_col, 17 + env_seed % 2)
    _set_hand(state, 0, ["cannon", "musketeer", "skeletons", "ice-golem"])
    _set_elixir(state, 0, 5000 + env_seed % 1501)
    engine.validate_state(state)
    seq_id = f"avoid-overcommit:{seq_idx}"
    captures: list[dict[str, Any]] = []
    for offset in range(_MAX_SEQ_STEPS):
        hogs = [
            e for e in _live_own_troops(state)
            if str(getattr(e, "card_id", "")).replace("_", "-") in ("hog-rider", "cursed-hog")
        ]
        if not hogs:
            break
        record = _capture(
            context, env, family="avoid-overcommit", seq_id=seq_id,
            offset=offset, env_seed=env_seed, source=source,
        )
        if record is None:
            break
        captures.append(record)
        if live_hook is not None:
            live_hook(env, record, offset)
        _step_wait(env)
        if env.state is None or env.state.terminal:
            break
        state = env.state
    return captures


_BUILDERS: dict[str, Callable[..., list[dict[str, Any]]]] = {
    "opening-scout": _build_opening,
    "preserve-defense": _build_preserve,
    "counterpush-save": _build_counterpush,
    "defensive-timing": _build_defensive_timing,
    "hold-utility": _build_hold_utility,
    "avoid-overcommit": _build_avoid_overcommit,
}


# ---------------------------------------------------------------------------
# Pool generation, filtering, and quota balancing.
# ---------------------------------------------------------------------------


def _sequence_count(config: TimingConfig, family: str) -> int:
    total_weight = sum(config.family_weights.values())
    share = config.family_weights[family] / total_weight
    # Aim pool_factor * n_states candidates at ~5 captures per sequence.
    return max(4, int(round(config.pool_factor * config.n_states * share / 5.0)))


def generate_timing_pool(
    config: TimingConfig,
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> list[dict[str, Any]]:
    """Generate the full candidate pool (unbalanced, deterministic).

    ``live_hook``, when given, is invoked with the live environment after
    every capture (before the next WAIT step), e.g. for counterfactual
    search on the exact labeled state.  Offsets passed to the hook match
    the post-hoc ``record["offset"]`` numbering.
    """

    context = _TimingContext.build(config.seed)
    pool: list[dict[str, Any]] = []
    for family in TIMING_FAMILIES:
        for seq_idx in range(_sequence_count(config, family)):
            try:
                captures = _BUILDERS[family](context, config, seq_idx, live_hook=live_hook)
            except TeacherError:
                continue
            for offset, record in enumerate(captures):
                record["offset"] = offset
                record["provenance"]["sequence_offset"] = offset
                record["provenance"]["sequence_length"] = len(captures)
                pool.append(record)
    return pool


def replay_timing_sequences(
    config: TimingConfig,
    selections: Sequence[tuple[str, int]],
    live_hook: Callable[[Any, dict[str, Any], int], None] | None = None,
) -> None:
    """Rebuild selected ``(family, seq_idx)`` sequences, invoking the hook.

    Replays are bit-deterministic: the same seeds rebuild the same
    environments, so a second pass observes the identical labeled states
    as the original pool pass (verified by state-hash comparison in the
    search dataset builder).
    """

    context = _TimingContext.build(config.seed)
    for family, seq_idx in selections:
        if family not in _BUILDERS:
            raise TeacherError(f"unknown timing family for replay: {family!r}")
        try:
            _BUILDERS[family](context, config, int(seq_idx), live_hook=live_hook)
        except TeacherError:
            continue


def _hash_order(seed: int, record: dict[str, Any]) -> int:
    return _stable_seed(seed, "order", record["seq_id"], record["offset"])


def balance_timing_pool(
    pool: list[dict[str, Any]], config: TimingConfig
) -> tuple[list[DistillationSample], dict[str, Any]]:
    """Deterministically select a quota-balanced subset of the pool.

    Constraints: mode split near ``mode_target``; every family at or above
    ``family_min_share``; every WAIT duration within
    [``duration_min``, ``duration_max``] of WAITs; WAITs without legal PLAY
    capped at ``max_wait_without_play_share``.
    """

    if not pool:
        raise TeacherError("timing pool is empty; cannot balance")
    n_total = min(config.n_states, len(pool))
    n_wait_target = int(round(n_total * config.mode_target))
    waits = sorted(
        (r for r in pool if r["mode"] == 0),
        key=lambda r: _hash_order(config.seed, r),
    )
    plays = sorted(
        (r for r in pool if r["mode"] == 1),
        key=lambda r: _hash_order(config.seed, r),
    )
    # Cap WAITs with no legal PLAY (broke leftovers); strategic WAITs with
    # legal options stay.  Deterministic: hash order decides survivors.
    with_play = [r for r in waits if r["play_legal"]]
    without_play = [r for r in waits if not r["play_legal"]]
    keep_without = min(len(without_play), int(round(n_wait_target * config.max_wait_without_play_share)))
    waits = sorted(with_play + without_play[:keep_without], key=lambda r: _hash_order(config.seed, r))
    if len(waits) < n_wait_target:
        raise TeacherError(
            f"timing pool holds only {len(waits)} usable WAITs for {n_wait_target} requested"
        )

    # Duration quotas: equal shares sit inside every [min, max] band.
    per_duration = n_wait_target // 4
    by_duration: dict[int, list[dict[str, Any]]] = {d: [] for d in range(4)}
    for record in waits:
        by_duration[record["duration"]].append(record)
    for duration, rows in by_duration.items():
        if len(rows) < per_duration:
            raise TeacherError(
                f"duration {duration} has {len(rows)} WAITs, need {per_duration}"
            )
    selected_waits: list[dict[str, Any]] = []
    for duration in range(4):
        selected_waits.extend(by_duration[duration][:per_duration])
    # Fill remainder (rounding) from the scarcest durations first.
    remainder = n_wait_target - len(selected_waits)
    if remainder:
        counts = {d: per_duration for d in range(4)}
        taken = {id(r) for r in selected_waits}
        leftovers = [r for r in waits if id(r) not in taken]
        leftovers.sort(key=lambda r: (counts[r["duration"]], _hash_order(config.seed, r)))
        for record in leftovers[:remainder]:
            selected_waits.append(record)
            counts[record["duration"]] += 1

    n_play_target = n_total - len(selected_waits)
    if len(plays) < n_play_target:
        raise TeacherError(
            f"timing pool holds only {len(plays)} PLAYs for {n_play_target} requested"
        )
    # Family-stratified PLAY picks (round-robin over hash-ordered families).
    by_family: dict[str, list[dict[str, Any]]] = {f: [] for f in TIMING_FAMILIES}
    for record in plays:
        by_family[record["family"]].append(record)
    selected_plays: list[dict[str, Any]] = []
    while len(selected_plays) < n_play_target:
        progressed = False
        for family in TIMING_FAMILIES:
            if len(selected_plays) >= n_play_target:
                break
            rows = by_family[family]
            if len(rows) > len([r for r in selected_plays if r["family"] == family]):
                selected_plays.append(
                    rows[len([r for r in selected_plays if r["family"] == family])]
                )
                progressed = True
        if not progressed:
            break

    selected = selected_waits + selected_plays
    stats = _pool_stats(selected)
    _assert_balance(stats, config, n_total)
    samples = [_to_sample(record, index) for index, record in enumerate(selected)]
    return samples, stats


def _pool_stats(selected: list[dict[str, Any]]) -> dict[str, Any]:
    from collections import Counter

    waits = [r for r in selected if r["mode"] == 0]
    families = Counter(r["family"] for r in selected)
    durations = Counter(r["duration"] for r in waits)
    two_plus = sum(1 for r in waits if r["legal_cards"] >= 2)
    return {
        "n": len(selected),
        "n_wait": len(waits),
        "n_play": len(selected) - len(waits),
        "wait_share": len(waits) / max(1, len(selected)),
        "family_share": {f: families.get(f, 0) / max(1, len(selected)) for f in TIMING_FAMILIES},
        "family_n": dict(families),
        "duration_share": {d: durations.get(d, 0) / max(1, len(waits)) for d in range(4)},
        "duration_n": {d: durations.get(d, 0) for d in range(4)},
        "wait_with_play_share": sum(1 for r in waits if r["play_legal"]) / max(1, len(waits)),
        "wait_with_two_plus_share": two_plus / max(1, len(waits)),
    }


def _assert_balance(stats: dict[str, Any], config: TimingConfig, n_total: int) -> None:
    problems: list[str] = []
    if abs(stats["wait_share"] - config.mode_target) > config.mode_tol + 1e-9:
        problems.append(f"mode split {stats['wait_share']:.3f} outside target")
    for family, share in stats["family_share"].items():
        if share < config.family_min_share - 1e-9:
            problems.append(f"family {family} share {share:.3f} below minimum")
    for duration, share in stats["duration_share"].items():
        if not (config.duration_min - 1e-9 <= share <= config.duration_max + 1e-9):
            problems.append(f"duration {duration} share {share:.3f} outside band")
    if stats["wait_with_play_share"] < 0.70 - 1e-9:
        problems.append("WAIT-with-legal-PLAY below 0.70")
    if stats["wait_with_two_plus_share"] < 0.40 - 1e-9:
        problems.append("WAIT-with-2+-cards below 0.40")
    if problems:
        raise TeacherError("timing balance unsatisfiable: " + "; ".join(problems))


def _to_sample(record: dict[str, Any], index: int) -> DistillationSample:
    provenance = dict(record["provenance"])
    provenance["index"] = index
    return DistillationSample(
        family=record["family"],
        raster=record["raster"],
        global_features=record["global_features"],
        entity_tokens=record["entity_tokens"],
        entity_mask=record["entity_mask"],
        hand_tokens=record["hand_tokens"],
        opp_hand_probs=_uniform_belief(),
        opp_out_of_cycle=_empty_out_of_cycle(),
        opp_elixir_interval=np.asarray([0.0, 10.0], dtype=np.float32),
        event_history=np.zeros((16, 8), dtype=np.float32),
        legal_play=record["legal_play"],
        legal_wait=record["legal_wait"],
        own_elixir=record["own_elixir"],
        target=record["target"],
        soft_placement=record["soft_placement"],
        provenance=provenance,
    )


_BELIEF_CACHE: dict[str, np.ndarray] = {}


def _uniform_belief() -> np.ndarray:
    cached = _BELIEF_CACHE.get("probs")
    if cached is None:
        cached = np.full((128,), 1.0 / 128, dtype=np.float32)
        _BELIEF_CACHE["probs"] = cached
    return np.array(cached, dtype=np.float32)


def _empty_out_of_cycle() -> np.ndarray:
    return np.zeros((128,), dtype=bool)


def generate_timing_dataset(config: TimingConfig) -> tuple[list[DistillationSample], dict[str, Any]]:
    """Generate a quota-balanced timing dataset and its balance report."""

    pool = generate_timing_pool(config)
    return balance_timing_pool(pool, config)


def generate_timing_natural(config: TimingConfig) -> tuple[list[DistillationSample], dict[str, Any]]:
    """Generate an unbalanced natural-distribution timing set.

    Same sequence generator, no quota selection: the pool in deterministic
    hash order (representative of pool composition), truncated to
    ``n_states``.  This mirrors what real rollouts yield.
    """

    pool = generate_timing_pool(config)
    pool.sort(key=lambda r: _hash_order(config.seed + 999_983, r))
    selected = pool[: min(config.n_states, len(pool))]
    if not selected:
        raise TeacherError("timing pool is empty; cannot build natural set")
    stats = _pool_stats(selected)
    return [_to_sample(record, index) for index, record in enumerate(selected)], stats


def describe_pool(config: TimingConfig) -> dict[str, Any]:
    """Report raw pool composition (quota diagnostics, no selection)."""

    return _pool_stats(generate_timing_pool(config))


__all__ = [
    "TIMING_FAMILIES",
    "TIMING_GENERATOR_VERSION",
    "TimingConfig",
    "balance_timing_pool",
    "describe_pool",
    "generate_timing_dataset",
    "generate_timing_natural",
    "generate_timing_pool",
    "replay_timing_sequences",
]
